### PR TITLE
Add Amplitude adapter

### PR DESCRIPTION
**Pull request by chrismllr**
Add an adapter for Amplitude:
https://developers.amplitude.com/
https://amplitude.com/

### CODE REVIEW

**Comment by jherdman** [comment]
Are you able to:

- [ ] Rebase
- [ ] Refactor into a native class?

**Comment by chrismllr** [comment]
@jherdman certainly! I’ll spend some time this week.

**Comment by chrismllr** [comment]
@jherdman  Done-- let me know if there are any other minor updates to make based on new patterns being used!

**Comment by jherdman** [comment]
Many thanks!

**Pull request merged**
