### PR TITLE
Update mixpanel adapter tracking code

### PR DESCRIPTION
**Pull request by nselikoff**

### CODE REVIEW

**Comment by jherdman** [comment]
@nselikoff are you interested in making these changes still? If so, do you mind rebasing against master?

**Comment by jherdman** [comment]
#254 is likely related.

**Comment by nselikoff** [comment]
@jherdman I rebased against master and double checked that the snippet matches the latest from the mixpanel docs. The tests run and the dummy app looks good (though FYI, I had to temporarily change the token to my own to test the dummy app).

Also, I happened to notice that for folks implementing Mixpanel in the EU, there's a different config required: https://developer.mixpanel.com/docs/implement-mixpanel#implementing-mixpanel-in-the-european-union-eu

I'll create a new issue for this if there isn't one already.

**Comment by jherdman** [comment]
> I'll create a new issue for this if there isn't one already.

That'd be great!

**Pull request merged**
