### PR TITLE
Support optional Mixpanel init config options

### PR DESCRIPTION
**Pull request by vladucu**
Adds support for other optional config options for Mixpanel's `init` call.
See https://developer.mixpanel.com/docs/javascript-full-api-reference#mixpanelinit for more

### CODE REVIEW

**Comment by jherdman** [comment]
Are you amenable to tackling the feature requested in ##229 too?

**Comment by vladucu** [comment]
> Are you amenable to tackling the feature requested in ##229 too?

This change should allow customizing `api_host` too, while keeping the existing default. Let me know if this is not what you were referring to

**Comment by JamesS-M** [comment]
What's the status of this?

**Comment by jherdman** [comment]
@vladucu this could use a rebase if you have the time. Once you do so I'm happy to merge.

**Comment by vladucu** [comment]
@jherdman rebased. Thanks!

**Review by jherdman — APPROVED** [review]

**Comment by jherdman** [comment]
I believe this resolves #229 too.

**Pull request merged**
